package GUI;

import java.net.*;
import java.io.*;
import javax.swing.JFileChooser;

public class VistaCliente extends javax.swing.JFrame {

    String b = "Bienvenido ";
    String r = "Ruta asignada: C:/redes/";
    Login login;

    /**
     * Creates new form VistaCliente
     */
    public VistaCliente() {
        initComponents();
        login = new Login();
        //String b = "Bienvenido ";
        lblBienvenido.setText(b + login.nombre);
        lblRuta.setText(r + login.nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSubir = new javax.swing.JButton();
        lblBienvenido = new javax.swing.JLabel();
        lblRuta = new javax.swing.JLabel();
        btnV = new javax.swing.JButton();
        btnServidor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese el archivo");

        btnSubir.setText("Subir Archivo");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        lblBienvenido.setText("Bienvenido");

        lblRuta.setText("Ruta asignada: \"C:\\redes\\\"");

        btnV.setText("Volver");
        btnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVActionPerformed(evt);
            }
        });

        btnServidor.setText("Subir a Servidor");
        btnServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServidorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblBienvenido))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnSubir)
                        .addGap(58, 58, 58)
                        .addComponent(btnServidor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnV))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblBienvenido)
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubir)
                    .addComponent(btnServidor))
                .addGap(27, 27, 27)
                .addComponent(lblRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnV)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void enviarACarpeta(String nombreArchivo, String nombre) {

        try {

            InetAddress ip = InetAddress.getByName("192.168.1.5");

            // Creamos el Socket con la direccion y elpuerto de comunicacion
            Socket socket = new Socket(ip, 4400);
            socket.setSoTimeout(20000);
            socket.setKeepAlive(true);

            System.out.println("yu " + nombreArchivo);
            File file = new File(nombreArchivo);

            int tamañoArchivo = (int) file.length();

            DataOutputStream dos = new DataOutputStream(socket.getOutputStream());

            System.out.println("Enviando Archivo: " + nombre);

            // Enviamos el nombre del archivo
            dos.writeUTF(nombre);
            dos.writeInt(tamañoArchivo);
            dos.writeUTF(login.nombre);
            System.out.println("Enviando Archivo: " + tamañoArchivo);

            FileInputStream fis = new FileInputStream(nombreArchivo);
            BufferedInputStream bis = new BufferedInputStream(fis);
            BufferedOutputStream bos = new BufferedOutputStream(socket.getOutputStream());

            // Creamos un array de tipo byte con el tamaño del archivo
            byte[] buffer = new byte[tamañoArchivo];

            bis.read(buffer);

            // Realizamos el envio de los bytes que conforman el archivo
            for (int i = 0; i < buffer.length; i++) {
                bos.write(buffer[i]);
            }

            System.out.println("Archivo Enviado: " + file.getName());
            bis.close();
            bos.close();
            socket.close();
        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    public void enviarAServidor(String nombreArchivo, String nombre) {

        try {

            InetAddress ip = InetAddress.getByName("192.168.1.5");

            // Creamos el Socket con la direccion y elpuerto de comunicacion
            Socket socket = new Socket(ip, 4400);
            socket.setSoTimeout(20000);
            socket.setKeepAlive(true);

            File file = new File(nombreArchivo);

            int tamañoArchivo = (int) file.length();

            DataOutputStream dos = new DataOutputStream(socket.getOutputStream());

            System.out.println("Enviando Archivo: " + nombre);

            // Enviamos el nombre del archivo
            dos.writeUTF(nombre);
            dos.writeInt(tamañoArchivo);
            dos.writeUTF("servidor");
            System.out.println("Enviando Archivo: " + tamañoArchivo);

            FileInputStream fis = new FileInputStream(nombreArchivo);
            BufferedInputStream bis = new BufferedInputStream(fis);
            BufferedOutputStream bos = new BufferedOutputStream(socket.getOutputStream());

            // Creamos un array de tipo byte con el tamaño del archivo
            byte[] buffer = new byte[tamañoArchivo];

            bis.read(buffer);

            // Realizamos el envio de los bytes que conforman el archivo
            for (int i = 0; i < buffer.length; i++) {
                bos.write(buffer[i]);
            }

            System.out.println("Archivo Enviado: " + file.getName());
            bis.close();
            bos.close();
            socket.close();
        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }
    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        JFileChooser fChooser = new JFileChooser();
        int respuesta = fChooser.showOpenDialog(this);

        if (respuesta == JFileChooser.APPROVE_OPTION) {

            File archivoElegido = fChooser.getSelectedFile();
            System.out.println(archivoElegido.getAbsolutePath() + "&" + archivoElegido.getName());
            enviarACarpeta(archivoElegido.getAbsolutePath(), archivoElegido.getName());
    }//GEN-LAST:event_btnSubirActionPerformed
    }
    private void btnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVActionPerformed
        System.out.println("aca");
        Login log = new Login();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVActionPerformed

    private void btnServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServidorActionPerformed
        JFileChooser fChooser = new JFileChooser();
        int respuesta = fChooser.showOpenDialog(this);

        if (respuesta == JFileChooser.APPROVE_OPTION) {

            File archivoElegido = fChooser.getSelectedFile();
            System.out.println(archivoElegido.getAbsolutePath() + "&" + archivoElegido.getName());
            enviarAServidor(archivoElegido.getAbsolutePath(), archivoElegido.getName());
        }
    }//GEN-LAST:event_btnServidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnServidor;
    private javax.swing.JButton btnSubir;
    private javax.swing.JButton btnV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblRuta;
    // End of variables declaration//GEN-END:variables
}
